export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_FOLLOWS_REQUEST = "USER_FOLLOWS_REQUEST";
export const USER_FOLLOWS_SUCCESS = "USER_FOLLOWS_SUCCESS";
export const USER_FOLLOWS_FAIL = "USER_FOLLOWS_FAIL";

export const USER_FOLLOWS_TAGS_REQUEST = "USER_FOLLOWS_TAGS_REQUEST";
export const USER_FOLLOWS_TAGS_SUCCESS = "USER_FOLLOWS_TAGS_SUCCESS";
export const USER_FOLLOWS_TAGS_FAIL = "USER_FOLLOWS_TAGS_FAIL";
